
/*
-- Author:  Sac
-- _Date: 2024
-- Description: This stored procedure displays the information from the Log generated by the CDC
--Parameters: DataBase Name
exec sp_InfoCDCTracker 'myDataBase'
*/


CREATE PROCEDURE sp_InfoCDCTracker
@databasename varchar(max)
AS 
BEGIN

--Activar CDC
exec ('use ' + @databasename);
SELECT * FROM cdc.captured_columns;
SELECT * FROM cdc.change_tables;
SELECT * FROM cdc.ddl_history;
SELECT * FROM cdc.index_columns;
SELECT * FROM cdc.lsn_time_mapping;
END